x-common-variables: &common-variables
  POSTGRES_DB: books
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432

services:
  postgres:
    image: postgres:17-alpine
    container_name: db.books.com
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment: *common-variables
    volumes:
      - pg_books_data:/var/lib/postgres/data/

  books-api:
    image: gochallenge:latest
    container_name: api.books.com
    environment:
      DATABASE_URL: "host=postgres user=postgres password=postgres dbname=books sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg_books_data:
    